### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by demisx** [loopj/node-sidekiq#5]
Hi. I am wondering wether the current version is production ready and how it really compares to the Ruby version of sidekiq feature-wise. I've enjoyed working with the latter in the post, so would love to see a peer node version as well. Would you say it's ready for mission critical apps or does it need some polishing? There is not much activity with this project and this is a concern. Thank you.

**Comment by loopj** [comment]
Hey @demisx, this is definitely production-ready, we're using it in large scale apps.

This node module is not intended to be a replacement for sidekiq, rather a way to add jobs from node to be executed in ruby apps.

**Comment by demisx** [comment]
Bummer, I thought this was the node version of Sidekiq. Thank you for clarifying. I'll continue searching for the node one.
